package vista;

import controlador.ControladorActividadPersonal;
import controlador.ControladorPersona;
import javax.swing.JOptionPane;

public class CrearActividadPersonal extends javax.swing.JFrame {

    /**
     * Creates new form CrearActividadPersonal
     */
    private ControladorPersona controlador;
    private ControladorActividadPersonal controladorActividadPersonal = new ControladorActividadPersonal();

    public CrearActividadPersonal() {
        initComponents();
        panelDescripcion.setVisible(false);
    }

    public CrearActividadPersonal(ControladorPersona controlador) {
        initComponents();
        this.controlador = controlador;
        panelDescripcion.setVisible(false);
    }

    private boolean camposLlenos() {
        if (txtNombre.getText().length() < 0 && DateChooserFecha.getDate().equals(null)) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DateChooserFecha = new com.toedter.calendar.JDateChooser();
        panelNotificar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxHora = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        c = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxSegundos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        panelDescripcion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        checkBtnDescripcion = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 112, 192));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear actividad personal.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 480, 44);

        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtNombre);
        txtNombre.setBounds(170, 100, 370, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 100, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 140, 70, 30);
        jPanel2.add(DateChooserFecha);
        DateChooserFecha.setBounds(170, 140, 370, 30);

        panelNotificar.setBackground(new java.awt.Color(0, 112, 192));
        panelNotificar.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hora: ");
        panelNotificar.add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 30);

        cbxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));
        panelNotificar.add(cbxHora);
        cbxHora.setBounds(90, 20, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Minutos:");
        panelNotificar.add(jLabel4);
        jLabel4.setBounds(220, 20, 70, 30);

        c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53 ", "54", "55", "56", "57", "58", "59" }));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        panelNotificar.add(c);
        c.setBounds(290, 20, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Segundos:");
        panelNotificar.add(jLabel5);
        jLabel5.setBounds(420, 20, 80, 30);

        cbxSegundos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53 ", "54", "55", "56", "57", "58", "59" }));
        panelNotificar.add(cbxSegundos);
        cbxSegundos.setBounds(500, 20, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("*");
        panelNotificar.add(jLabel8);
        jLabel8.setBounds(620, 20, 20, 30);

        jPanel2.add(panelNotificar);
        panelNotificar.setBounds(0, 180, 650, 60);

        panelDescripcion.setBackground(new java.awt.Color(0, 112, 192));
        panelDescripcion.setLayout(null);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        panelDescripcion.add(jScrollPane1);
        jScrollPane1.setBounds(20, 0, 610, 110);

        jPanel2.add(panelDescripcion);
        panelDescripcion.setBounds(0, 310, 650, 110);

        checkBtnDescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkBtnDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        checkBtnDescripcion.setText("Descripción.");
        checkBtnDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnDescripcionActionPerformed(evt);
            }
        });
        jPanel2.add(checkBtnDescripcion);
        checkBtnDescripcion.setBounds(20, 250, 110, 24);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Los campos con (*) son de uso obligatorio.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 70, 330, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("*");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(550, 100, 20, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("*");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(550, 140, 20, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 650, 430);

        jPanel3.setBackground(new java.awt.Color(0, 112, 192));
        jPanel3.setLayout(null);

        btnGuardar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar);
        btnGuardar.setBounds(520, 10, 110, 30);

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir.");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalir);
        btnSalir.setBounds(20, 10, 70, 29);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 430, 650, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 510);

        setSize(new java.awt.Dimension(668, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkBtnDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnDescripcionActionPerformed
        if (checkBtnDescripcion.isSelected()) {
            panelDescripcion.setVisible(true);
        } else {
            panelDescripcion.setVisible(false);
        }
    }//GEN-LAST:event_checkBtnDescripcionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (camposLlenos()) {
            controladorActividadPersonal.getActividadPersonal().setNombre(txtNombre.getText());
            controladorActividadPersonal.getActividadPersonal().setDescripcion(txtDescripcion.getText());
            controladorActividadPersonal.getActividadPersonal().setEstado("activo");
            controladorActividadPersonal.getActividadPersonal().setFechaEntrega(DateChooserFecha.getDate());
            controladorActividadPersonal.getActividadPersonal().setId(controladorActividadPersonal.numeroEmpleados() + 1);
            controladorActividadPersonal.getActividadPersonal().setHora(((String) cbxHora.getSelectedItem()) + ":" + ((String) cbxHora.getSelectedItem()) + ":" + ((String) cbxSegundos.getSelectedItem()));
            controladorActividadPersonal.getActividadPersonal().setPersona_id(controlador.getPersona().getId());
            if (controladorActividadPersonal.guardarActividadPersonal()) {
                JOptionPane.showMessageDialog(null, "Se guardo alarma correctamente");
                this.dispose();
                GestionarActividadesPersonalesVista apv = new GestionarActividadesPersonalesVista(controlador);
                apv.setLocationRelativeTo(null);
                apv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tiene campos vacios");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        GestionarActividadesPersonalesVista apv = new GestionarActividadesPersonalesVista(controlador);
        apv.setLocationRelativeTo(null);
        apv.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearActividadPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearActividadPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearActividadPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearActividadPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearActividadPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooserFecha;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> c;
    private javax.swing.JComboBox<String> cbxHora;
    private javax.swing.JComboBox<String> cbxSegundos;
    private javax.swing.JCheckBox checkBtnDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDescripcion;
    private javax.swing.JPanel panelNotificar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
